name: build

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Setup GCP
      uses: google-github-actions/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        project_id: ${{ secrets.GCS_PROJECT }}
        export_default_credentials: true

    - name: Sync service environment
      run: |
        gsutil cp gs://${{ secrets.GCS_SERVICE_ENV }}/config.json config.json

    - name: Unit Test
      run: |
        make test
        bash <(curl -s https://codecov.io/bash)

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - run: |
        gcloud auth configure-docker -q

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: gcr.io/${{ secrets.GCS_PROJECT }}/reverse-proxy:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
